builds:
- id: gsuite_auth
  binary: gsuite_auth
  gobinary: go1.21.6
  goos:
    - linux
    - darwin
- id: qrcreator
  dir: qrcreator
  main: qrcreator.go
  binary: qrcreator
  gobinary: go1.21.6
  goos:
    - linux
    - darwin
