docker run \
-p 5000:5000 \
-e VPNAUTH_SQLALCHEMY_DATABASE_URI='postgresql+psycopg2://otpserver:otpserver@host.docker.internal:5432/otpserver' \
-e VPNAUTH_GSUITE_DOMAIN=$VPNAUTH_GSUITE_DOMAIN \
-e VPNAUTH_GOOGLE_CLIENT_ID=$VPNAUTH_GOOGLE_CLIENT_ID \
-e VPNAUTH_GOOGLE_CLIENT_SECRET=$VPNAUTH_GOOGLE_CLIENT_SECRET \
-e VPNAUTH_DYNAMODB_ACCESS_KEY=$VPNAUTH_DYNAMODB_ACCESS_KEY \
-e VPNAUTH_DYNAMODB_SECRET_KEY=$VPNAUTH_DYNAMODB_SECRET_KEY \
-e VPNAUTH_DYNAMODB_REGION=$VPNAUTH_DYNAMODB_REGION \
-e VPNAUTH_OVPN_BASE_DIR='/tmp' \
docker.io/library/vpnauth:latest
# ghcr.io/looprock/vpnauth:latest
# vpnauth:latest
# -e VPNAUTH_TOTP_ENCRYPTION_KEY=$VPNAUTH_TOTP_ENCRYPTION_KEY \
